# **Implementasi K-Means Clustering**

## K-Means Clustering

K-Means Clustering adalah salah satu algoritma dalam menentukan klasifikasi terhadap objek berdasarkan attribut / fitur dari objek tersebut kedalam K kluster/partisi. K adalah angka positif yang menyatakan jumlah grup/kluster partisi terhadap objek. Pemartisian data dilakukan dengan mencari nilai jarak minimum antara data dan nilai ***centroid*** yang telah di set baik secara random atau pun dengan ***Initial Set of Centroids***, kita juga dapat menentukan nilai centroid berdasarkan ***K object*** yang berurutan

***Centroid*** adalah nilai rata-rata aritmetik dari sebuah bentuk objek dari seluruh titik dalam objek tersebut. Penerapan K-Means Clustering ini dapat dilakukan dengan prosedur step by step berikut :

- Siapkan data training berbentuk vector.
- Set nilai K cluster.
- Set nilai awal centroids.
- Hitung jarak antara data dan centroid menggunakan rumus ***Euclidean Distance***.
 
  Rumus Menghitung Jarak :

  > $ùôô(p,q) =  \sqrt {Œ£_{i=1}^{n}(q_i - p_i)^2} $
  
  ```
  ket :
    p,q	    =	dua titik di ruang-n Euclidean
    qi,pi    =	vektor Euclidean, dimulai dari asal ruang (titik awal)
    n        =	ruang-n

  ```
  
  
- Partisi data berdasarkan nilai minimum.
- Kemudian lakukan iterasi selama partisi data masih bergerak (tidak ada lagi objek yang bergerak ke partisi lain), bila masih maka ke poin 3.
- Bila grup data sekarang sama dengan grup data sebelumnya, maka hentikan iterasi.
- Data telah dipartisi sesuai nilai centroid akhir.

## Implementasi ke Bahasa Pemrograman Python

### Persiapan data

Data yang akan digunakan adalah data iris, yang dapat diperoleh [disini](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

In [942]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
#the imported dataset does not have the required column names so lets add it
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
irisdata = pd.read_csv(url, names=colnames)
irisdata

     sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

### Mengubah Label menjadi angka

In [943]:
irisdata['Class'] = pd.Categorical(irisdata["Class"])
irisdata["Class"] = irisdata["Class"].cat.codes
irisdata

     sepal-length  sepal-width  petal-length  petal-width  Class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]

### Menentukan Attribute yang akan dipakai

Pada kasus ini menggunakan `attribute` dari 0 sampai 4

In [944]:
x = irisdata.values[:, 0:4]
y = irisdata.values[:, 4]
# delete 'variety' column
df_without_label = irisdata.drop(columns=["Class"])
df_without_label

     sepal-length  sepal-width  petal-length  petal-width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

### Menentukan Cluster dan Menghitung jarak

Pada Kasus ini, cluster yang ditentukan adalah **3**

In [945]:
from sklearn.cluster import KMeans
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

# Number of clusters
kmeans = KMeans(n_clusters=3)
# Fitting the input data
kmeans = kmeans.fit(x)
# Getting the cluster labels
labels = kmeans.predict(x)
# Centroid values
centroids = kmeans.cluster_centers_
hasil = kmeans.fit_transform(x)
hasil

array([[0.14694217, 3.41925061, 5.0595416 ],
       [0.43816892, 3.39857426, 5.11494335],
       [0.41230086, 3.56935666, 5.27935534],
       [0.51883716, 3.42240962, 5.15358977],
       [0.19796969, 3.46726403, 5.10433388],
       [0.68380699, 3.14673162, 4.68148797],
       [0.41520116, 3.51650264, 5.21147652],
       [0.0599333 , 3.33654987, 5.00252706],
       [0.80099438, 3.57233779, 5.32798107],
       [0.36659514, 3.3583767 , 5.06790865],
       [0.48784424, 3.32449131, 4.89806763],
       [0.25138019, 3.31126872, 4.9966845 ],
       [0.49192682, 3.46661272, 5.19103612],
       [0.90906105, 3.90578362, 5.65173594],
       [1.02019214, 3.646649  , 5.10804455],
       [1.21309192, 3.49427881, 4.88564095],
       [0.66241377, 3.495248  , 5.03090587],
       [0.1509702 , 3.38444981, 5.02342022],
       [0.82848778, 3.11245944, 4.61792995],
       [0.39898872, 3.37738931, 4.97213426],
       [0.46172719, 3.07471224, 4.6955761 ],
       [0.33762701, 3.31506588, 4.9236821 ],
       [0.64435394, 3.93167253, 5.59713396],
       [0.37946278, 3.01233762, 4.68193765],
       [0.4845534 , 3.06241269, 4.75095704],
       [0.44180539, 3.19414543, 4.90772894],
       [0.20782685, 3.17967089, 4.84545508],
       [0.21815591, 3.30941724, 4.93969029],
       [0.2097427 , 3.37648183, 5.01833618],
       [0.40198507, 3.31272968, 5.02954567],
       [0.40495926, 3.26550651, 4.98608729],
       [0.42566654, 3.18083736, 4.79550372],
       [0.72442529, 3.53142353, 5.06520776],
       [0.9282198 , 3.57102821, 5.04438334],
       [0.36659514, 3.3583767 , 5.06790865],
       [0.34524194, 3.56904033, 5.25071556],
       [0.5287646 , 3.43783276, 5.02368214],
       [0.36659514, 3.3583767 , 5.06790865],
       [0.75550778, 3.66205264, 5.40750095],
       [0.11131936, 3.31092773, 4.9664149 ],
       [0.19181241, 3.49764675, 5.14520862],
       [1.23935144, 3.60850034, 5.38423754],
       [0.66602703, 3.68120561, 5.40847417],
       [0.38986151, 3.14278239, 4.78803478],
       [0.60761172, 3.00585191, 4.59828494],
       [0.47370033, 3.39468045, 5.11844067],
       [0.41855943, 3.32788568, 4.92421655],
       [0.4673243 , 3.51879523, 5.23766854],
       [0.41132955, 3.34104251, 4.92859681],
       [0.14139307, 3.40601705, 5.08216833],
       [3.97889331, 1.22697525, 1.25489071],
       [3.57569462, 0.684141  , 1.44477759],
       [4.13182671, 1.17527644, 1.01903626],
       [3.00672446, 0.73153652, 2.45978458],
       [3.7451291 , 0.63853451, 1.3520017 ],
       [3.34604124, 0.26937898, 1.88009327],
       [3.74149596, 0.76452634, 1.28902785],
       [2.233829  , 1.58388575, 3.37155487],
       [3.70928457, 0.75582717, 1.41123804],
       [2.79706847, 0.85984838, 2.58955659],
       [2.5937602 , 1.53611907, 3.27864111],
       [3.16815277, 0.32426175, 1.90055758],
       [3.07805003, 0.80841374, 2.38073698],
       [3.64323922, 0.39674141, 1.45909603],
       [2.50973943, 0.87269542, 2.60303733],
       [3.59544045, 0.87306498, 1.50822767],
       [3.36487622, 0.41229163, 1.85387593],
       [2.9438057 , 0.53579956, 2.25517257],
       [3.70189033, 0.6367639 , 1.74778451],
       [2.80399572, 0.71254917, 2.49557781],
       [3.79431048, 0.7093731 , 1.37094403],
       [3.02079327, 0.46349013, 2.06563694],
       [3.98757972, 0.69373966, 1.29106776],
       [3.60060995, 0.43661144, 1.57547425],
       [3.37188256, 0.54593856, 1.70495043],
       [3.55977415, 0.74313017, 1.52298639],
       [4.00819061, 0.98798453, 1.18965415],
       [4.20328348, 1.06739835, 0.84636259],
       [3.47148268, 0.21993519, 1.61913335],
       [2.42231129, 1.0243726 , 2.77868071],
       [2.73312861, 0.86396528, 2.6440625 ],
       [2.61755458, 0.97566381, 2.75566654],
       [2.82736485, 0.55763082, 2.32254696],
       [4.06974102, 0.73395781, 1.22324554],
       [3.33538484, 0.57500396, 1.9942056 ],
       [3.47050313, 0.68790275, 1.61049622],
       [3.87556344, 0.92700552, 1.19803047],
       [3.55803204, 0.61459444, 1.81572464],
       [2.93107352, 0.50830256, 2.20430516],
       [2.9382294 , 0.6291191 , 2.40438484],
       [3.23221163, 0.48790256, 2.14635877],
       [3.54152397, 0.38266958, 1.52402278],
       [2.94020271, 0.49185351, 2.26286106],
       [2.27868208, 1.5485635 , 3.33648305],
       [3.07720523, 0.3856087 , 2.16211718],
       [3.00931753, 0.44284695, 2.11299567],
       [3.05790647, 0.3449879 , 2.07973003],
       [3.29423618, 0.37241653, 1.76829182],
       [1.98584793, 1.66064034, 3.44291999],
       [2.98784069, 0.38393196, 2.16527941],
       [5.23002792, 2.0445799 , 0.77731871],
       [4.13627755, 0.85382472, 1.29757391],
       [5.2614059 , 2.05245342, 0.30610139],
       [4.63361544, 1.33089245, 0.65293923],
       [5.00335807, 1.72813078, 0.38458885],
       [6.06026336, 2.87401886, 1.14225684],
       [3.49158875, 1.07101875, 2.4108337 ],
       [5.59810611, 2.39730707, 0.78573677],
       [4.99343489, 1.67668563, 0.65454939],
       [5.60613878, 2.54158648, 0.8435596 ],
       [4.31086905, 1.17541367, 0.74552218],
       [4.46273369, 1.13563278, 0.75289837],
       [4.80907392, 1.59322675, 0.25958095],
       [4.11232197, 0.88917352, 1.48572618],
       [4.34524936, 1.20227628, 1.30303821],
       [4.57523682, 1.42273608, 0.68288333],
       [4.5953446 , 1.33403966, 0.50991553],
       [6.21652572, 3.20105585, 1.47791217],
       [6.4578628 , 3.20759942, 1.52971038],
       [4.0684631 , 0.82617494, 1.53708992],
       [5.07992047, 1.91251832, 0.26952816],
       [3.95277017, 0.81891975, 1.5334904 ],
       [6.17566126, 2.9794431 , 1.31149299],
       [4.05181342, 0.74269596, 1.10668455],
       [4.92666134, 1.75847731, 0.27627819],
       [5.27802918, 2.14580999, 0.52766931],
       [3.91887637, 0.62526165, 1.20765678],
       [3.94953061, 0.70228926, 1.16212743],
       [4.78292714, 1.4663925 , 0.54629196],
       [5.0624097 , 1.93773659, 0.59428255],
       [5.50890116, 2.31885342, 0.7312665 ],
       [5.99739877, 3.07340053, 1.43802246],
       [4.82261257, 1.51444141, 0.5605572 ],
       [4.10541009, 0.81536685, 1.05631592],
       [4.50652771, 1.23209127, 1.12133058],
       [5.75777665, 2.6381171 , 0.95311851],
       [4.84041238, 1.72401927, 0.73306362],
       [4.55574275, 1.31541133, 0.57903109],
       [3.83572575, 0.61011676, 1.29960041],
       [4.75659458, 1.60532899, 0.34794609],
       [4.97248348, 1.77481954, 0.3893492 ],
       [4.59738969, 1.53937059, 0.68403844],
       [4.13627755, 0.85382472, 1.29757391],
       [5.21259935, 2.00764279, 0.30952112],
       [5.09085376, 1.94554509, 0.50939919],
       [4.60751473, 1.44957743, 0.61173881],
       [4.21459274, 0.89747884, 1.10072376],
       [4.40998776, 1.17993324, 0.65334214],
       [4.59839015, 1.50889317, 0.83572418],
       [4.07622276, 0.83452741, 1.1805499 ]])

### Mengklasifikasikan Hasil

In [947]:
labels
if(labels[1] == 0):
    print(labels)
elif labels[57] ==2:
  # print(labels)
  mapping = {0:2, 1:0, 2:1}
  a = [mapping[i] for i in labels]
  print(a,end='')
elif labels[1]==1:
  mapping = {0:1, 1:0, 2:2}
  a = [mapping[i] for i in labels]
  print(a,end='')

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 2 2 2 1 2 2 2 2
 2 2 1 1 2 2 2 2 1 2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 1 2 2 2 1 2
 2 1]

### Menghitung Akurasi



Rumus Menghitung akurasi:
> $Akurasi = {{TP + TN}\over Total Data} * 100 \% $

```
  Ket:
  TP  = Jumlah data yang terklasifikasi True Positive
  TN  = Jumlah data yang terklasifikasi True Negative
  Jumlah Data = Jumlah data keseluruhan
```

Akurasi yang diperoleh dari hasil ***K-mean Clustering*** dengan data uji acak pada kasus ini sebesar:

In [948]:
# rumus akurasu
if(labels[1] == 0):
    accuracy = accuracy_score(y, labels)
elif labels[55]==2:
    accuracy = accuracy_score(y, a)
elif labels[1]==1:
    accuracy = accuracy_score(y, a)

accuracy

0.8933333333333333